const { DataTypes } = require('sequelize');
const sequelize = require('../db'); 
const User = require('./customUserModel'); // Adjusted to match your file structure

const Address = sequelize.define('Address', {
  id: {
    type: DataTypes.BIGINT,
    primaryKey: true,
    autoIncrement: true, // Handles GENERATED BY DEFAULT AS IDENTITY
    allowNull: false
  },
  lat: {
    type: DataTypes.STRING(200),
    allowNull: false
  },
  lng: {
    type: DataTypes.STRING(200),
    allowNull: false
  },
  address: {
    type: DataTypes.STRING(200),
    allowNull: false
  },
  landmark: {
    type: DataTypes.STRING(200),
    allowNull: false
  },
  label: {
    type: DataTypes.STRING(200),
    allowNull: false,
    // Common values: 'Home', 'Work', 'Other'
  },
  house_no: {
    type: DataTypes.STRING(200),
    allowNull: false
  },
  building_name: {
    type: DataTypes.STRING(200),
    allowNull: true
  },
  receiver_name: {
    type: DataTypes.STRING(200),
    allowNull: true
  },
  receiver_contact: {
    type: DataTypes.STRING(200),
    allowNull: true
  },
  // Foreign Key to User
  user_id: {
    type: DataTypes.BIGINT,
    allowNull: false,
    references: {
      model: 'user_customuser', // Ensure this matches your actual Users table name
      key: 'id'
    },
    onDelete: 'CASCADE', // Optional: deletes address if user is deleted
    onUpdate: 'CASCADE'
  }
}, {
  tableName: 'addresses',
  timestamps: true, // Set to false if you don't want createdAt/updatedAt
});

// Define Association (Recommended)
// You typically put this in your main associations file or index.js
User.hasMany(Address, { foreignKey: 'user_id' });
Address.belongsTo(User, { foreignKey: 'user_id' });

module.exports = Address;