const { DataTypes } = require('sequelize');
const sequelize = require('../db');

const Banner = sequelize.define('Banner', {
  id: {
    type: DataTypes.BIGINT,
    primaryKey: true,
    autoIncrement: true, // Handles GENERATED BY DEFAULT AS IDENTITY
    allowNull: false
  },
  img: {
    type: DataTypes.STRING(200),
    allowNull: false,
    validate: {
      notEmpty: true
    }
  },
  route: {
    type: DataTypes.STRING(100),
    allowNull: true // Default is true, but good to be explicit
  },
  is_active: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: true // Common practice for is_active
  },
  type: {
    type: DataTypes.STRING(100),
    allowNull: true
  },
  term: {
    type: DataTypes.STRING(100),
    allowNull: true
  }
}, {
  tableName: 'banners', // Force table name
  timestamps: false,     // Set to true if you want createdAt/updatedAt
});

module.exports = Banner;