const { DataTypes } = require('sequelize');
const sequelize = require('../db');

const Event = sequelize.define('Event', {
  id: {
    type: DataTypes.BIGINT,
    primaryKey: true,
    autoIncrement: true, // Maps to GENERATED BY DEFAULT AS IDENTITY
  },
  title: {
    type: DataTypes.STRING(200),
    allowNull: false,
  },
  description: {
    type: DataTypes.TEXT,
    allowNull: false,
  },
  location: {
    type: DataTypes.JSONB,
    allowNull: false,
  },
  date: {
    type: DataTypes.DATEONLY,
    allowNull: false,
  },
  time: {
    type: DataTypes.TIME,
    allowNull: false,
  },
  duration: {
    type: DataTypes.STRING(50),
    allowNull: false,
  },
  category: {
    type: DataTypes.JSONB,
    allowNull: false,
  },
  tags: {
    type: DataTypes.JSONB,
    allowNull: false,
  },
  organizer: {
    type: DataTypes.STRING(200),
    allowNull: false,
  },
  contact: {
    type: DataTypes.STRING(300),
  },
  email: {
    type: DataTypes.STRING(254),
    allowNull: false,
  },
  ticketcount: {
    type: DataTypes.INTEGER,
    allowNull: false,
  },
  is_active: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: true,
  },
  ticketoptions: {
    type: DataTypes.JSONB,
  },
  isFree: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false,
  },
  ticketPrice: {
    type: DataTypes.DECIMAL(10, 2),
  },
  imageUrl: {
    type: DataTypes.STRING(300),
    allowNull: false,
  },
  registrationUrl: {
    type: DataTypes.STRING(300),
  },
  recurrence: {
    type: DataTypes.STRING(50),
    allowNull: false,
  },
  user_id: {
    type: DataTypes.BIGINT,
  }
}, {
  tableName: 'events',
  timestamps: true,
});

module.exports = Event;